import { runNode } from "./run-utils.mjs";

// Keep the production gate deterministic and fast. Browser matrices, corpus
// sweeps, and exhaustive research checks run in the Full Quality workflow.
const CHECKS = [
  "scripts/write-build-metadata.mjs",
  "scripts/check-build-metadata.mjs",
  "scripts/check-js.mjs",
  "scripts/check-wasm-hardening.mjs",
  "scripts/check-no-main-thread-heavy-wasm.mjs",
  "scripts/check-tflite-worker-rpc.mjs",
  "scripts/check-web-imports.mjs",
  "scripts/check-browser-import-contract.mjs",
  "scripts/check-dom-contract.mjs",
  "scripts/check-workflow-contract.mjs",
  "scripts/check-product-guidance-contracts.mjs",
  "scripts/check-access-hierarchy.mjs",
  "scripts/check-external-test-access.mjs",
  "scripts/check-advanced-copy-contract.mjs",
  "scripts/check-regulatory-bundle-contract.mjs",
  "scripts/check-export-artifact-contract.mjs",
  "scripts/check-export-contract-documents.mjs",
  "scripts/check-cyclonedx-draft-profiles.mjs",
  "scripts/check-cyclonedx-perspective-audit.mjs",
  "scripts/check-conversion-receipt.mjs",
  "scripts/check-artifact-ir.mjs",
  "scripts/check-artifact-ir-import-boundary.mjs",
  "scripts/check-artifact-ir-consumers.mjs",
  "scripts/check-evidence-ui-contract.mjs",
  "scripts/check-html-entrypoints.mjs",
  "scripts/check-importmap-runtime-cache.mjs",
  "scripts/check-hash-contract.mjs",
  "scripts/check-package-verifier.mjs",
  "scripts/check-model-file-contract.mjs",
  "scripts/check-format-routing.mjs",
  "scripts/check-parser-robustness.mjs",
  "scripts/check-custom-targets.mjs",
  "scripts/check-metadata-model-adapters.mjs",
  "scripts/check-coreml-range-reader.mjs",
  "scripts/check-coreml-legacy-analysis.mjs",
  "scripts/check-coreml-mlprogram-analysis.mjs",
  "scripts/check-safetensors-quantization-contract.mjs",
  "scripts/check-executorch-analysis.mjs",
  "scripts/check-tflite-delegate-rulepack.mjs",
  "scripts/check-on-device-llm-v2.mjs",
  "scripts/check-tensorrt-static-preflight.mjs",
  "scripts/check-tensorrt-engine-inspector-capture.mjs",
  "scripts/check-execution-placement-evidence.mjs",
  "scripts/check-artifact-bundle.mjs",
  "scripts/check-tensor-inventory.mjs",
  "scripts/check-graph-topology.mjs",
  "scripts/check-onnx-quantization-contract.mjs",
  "scripts/check-onnx-type-sparse-contract.mjs",
  "scripts/check-onnx-shape-inference.mjs",
  "scripts/check-onnx-container-inference.mjs",
  "scripts/check-onnx-ml-value-inference.mjs",
  "scripts/check-onnx-ml-label-encoder.mjs",
  "scripts/check-onnx-ml-svm.mjs",
  "scripts/check-onnx-ml-tree-ensemble.mjs",
  "scripts/check-onnx-tfidf-vectorizer.mjs",
  "scripts/check-onnx-schema-legality.mjs",
  "scripts/check-onnx-extended-shape-inference.mjs",
  "scripts/check-onnx-shape-scope.mjs",
  "scripts/check-onnx-domain-analysis.mjs",
  "scripts/check-onnx-contract-conflict.mjs",
  "scripts/check-onnx-contract-conflict-corpus.mjs",
  "scripts/check-kernel-inspector-contract.mjs",
  "scripts/check-runtime-arena-memory.mjs",
  "scripts/check-runtime-profile-adapter.mjs",
  "scripts/check-tflite-runtime-info-adapter.mjs",
  "scripts/check-tflite-profile-info-adapter.mjs",
  "scripts/check-xnnpack-selector-evidence.mjs",
  "scripts/check-xnnpack-delegate-rulepack.mjs",
  "scripts/check-ort-rulepack-generated.mjs",
  "scripts/check-ort-artifact-precheck.mjs",
  "scripts/check-runtime-contract.mjs",
  "scripts/check-sw-assets.mjs",
  "scripts/check-service-worker-lifecycle.mjs",
  "scripts/check-sw-version.mjs",
  "scripts/check-size-utils.mjs",
  "scripts/check-private-wasm-registry.mjs",
  "scripts/check-private-wasm-contract.mjs",
  "scripts/check-ci-deploy-contract.mjs",
  "scripts/check-git-privacy.mjs",
  "scripts/check-worker-config.mjs",
];

for (const script of CHECKS) {
  await runNode(script);
}

console.log(`Deployment gate passed (${CHECKS.length} checks, no browser matrix).`);
