import { runNode } from "./run-utils.mjs";

const CHECKS = [
  "scripts/sync-version.mjs --check",
  "scripts/check-expected-output.mjs",
  "scripts/check-review-policy.mjs",
  "scripts/check-accelerator-binding.mjs",
  "scripts/check-mlbom-conservation.mjs",
  "scripts/check-placement-comparison.mjs",
  "scripts/check-runtime-accelerator-import.mjs",
  "scripts/check-static-audit-worker-client.mjs",
  "scripts/write-build-metadata.mjs",
  "scripts/check-build-metadata.mjs",
  "scripts/check-zenodo-release.mjs",
  "scripts/check-js.mjs",
  "scripts/check-wasm-hardening.mjs",
  "scripts/check-web-imports.mjs",
  "scripts/check-browser-import-contract.mjs",
  "scripts/check-dom-contract.mjs",
  "scripts/check-workflow-contract.mjs",
  "scripts/check-product-guidance-contracts.mjs",
  "scripts/check-access-hierarchy.mjs",
  "scripts/check-external-test-access.mjs",
  "scripts/check-external-test-page.mjs",
  "scripts/check-advanced-copy-contract.mjs",
  "scripts/check-deepbom-analysis-contract.mjs",
  "scripts/check-cli.mjs",
  "scripts/generate-cli-docs.mjs --check",
  "scripts/check-cli-automation.mjs",
  "scripts/check-nvidia-accelerator-profile.mjs",
  "scripts/check-remote-artifact-resolver.mjs",
  "scripts/check-artifact-ir.mjs",
  "scripts/check-cli-graph-export.mjs",
  "scripts/check-regulatory-bundle-contract.mjs",
  "scripts/check-export-artifact-contract.mjs",
  "scripts/check-public-evidence-package.mjs",
  "scripts/check-evidence-package-profiles.mjs",
  "scripts/check-evidence-package-profile-ui.mjs",
  "scripts/check-export-contract-documents.mjs",
  "scripts/check-interface-contract-comparison.mjs",
  "scripts/check-export-contract-viewer.mjs",
  "scripts/check-html-entrypoints.mjs",
  "scripts/check-discovery-metadata.mjs",
  "scripts/check-importmap-runtime-cache.mjs",
  "scripts/check-litert-runtime-assets.mjs",
  "scripts/check-hash-contract.mjs",
  "scripts/check-public-key-signature.mjs",
  "scripts/check-package-verifier.mjs",
  "scripts/check-model-file-contract.mjs",
  "scripts/check-format-routing.mjs",
  "scripts/check-parser-robustness-isolated.mjs",
  "scripts/generate-executorch-operator-signatures.mjs --check",
  "scripts/check-executorch-analysis.mjs",
  "scripts/check-format-quantization-isolation.mjs",
  "scripts/check-tflite-sparse-storage.mjs",
  "scripts/check-tflite-subgraph-inventory.mjs",
  "scripts/check-analysis-invariants.mjs",
  "scripts/check-custom-targets.mjs",
  "scripts/check-public-samples.mjs",
  "scripts/check-metadata-model-adapters.mjs",
  "scripts/check-tensor-numerical-integrity.mjs",
  "scripts/check-gguf-backend-contract.mjs",
  "scripts/check-gguf-runtime-environment.mjs",
  "scripts/check-coreml-legacy-analysis.mjs",
  "scripts/check-coreml-range-reader.mjs",
  "scripts/check-coreml-legacy-quantization-corpus.mjs",
  "scripts/check-coreml-classical-analysis.mjs",
  "scripts/check-coreml-mlprogram-analysis.mjs",
  "scripts/check-coreml-deployment-contract.mjs",
  "scripts/check-coreml-compute-plan.mjs",
  "scripts/check-format-quant-viewer.mjs",
  "scripts/check-evidence-treemap.mjs",
  "scripts/check-evidence-workbench.mjs",
  "scripts/check-format-capability-viewer.mjs",
  "scripts/check-backend-placement-projection.mjs",
  "scripts/check-tensorrt-static-preflight.mjs",
  "scripts/check-tensorrt-engine-inspector-capture.mjs",
  "scripts/check-tensorrt-native-collector.mjs",
  "scripts/check-tensorrt-llm-contract.mjs",
  "scripts/check-execution-placement-evidence.mjs",
  "scripts/check-execution-placement-viewer.mjs",
  "scripts/check-runtime-evidence-sidecar.mjs",
  "scripts/check-artifact-bundle.mjs",
  "scripts/check-on-device-llm-v2.mjs",
  "scripts/check-on-device-llm-viewer.mjs",
  "scripts/check-safetensors-architecture-corpus.mjs",
  "scripts/check-gguf-architecture-encoding-corpus.mjs",
  "scripts/check-coreml-mlprogram-corpus.mjs",
  "scripts/check-public-model-corpus.mjs",
  "scripts/check-curated-micro-corpus.mjs",
  "scripts/check-google-legacy-corpus.mjs",
  "scripts/check-quant-policy-corpus.mjs",
  "scripts/check-corpus-validation-provenance.mjs",
  "scripts/check-huggingface-community-corpus.mjs",
  "scripts/check-residual-coverage-ledger.mjs",
  "scripts/check-cyclonedx-20-quantization-evidence.mjs",
  "scripts/check-standardization-evidence.mjs",
  "scripts/check-public-multiformat-corpus.mjs",
  "scripts/check-onnx-extension-contract-corpus.mjs",
  "scripts/check-safetensors-quantization-contract.mjs",
  "scripts/check-safetensors-quantization-viewer.mjs",
  "scripts/check-safetensors-quantization-corpus.mjs",
  "scripts/check-tensor-inventory.mjs",
  "scripts/check-graph-topology.mjs",
  "scripts/check-explorer-question-view.mjs",
  "scripts/check-explorer-redesign.mjs",
  "scripts/check-explorer-redesign-viewer.mjs",
  "scripts/check-dynamic-shape-cost.mjs",
  "scripts/check-dynamic-shape-cost-viewer.mjs",
  "scripts/check-landscape-math.mjs",
  "scripts/check-research-visuals.mjs",
  "scripts/check-deployment-frontier.mjs",
  "scripts/check-deployment-frontier-viewer.mjs",
  "scripts/check-deployment-delta.mjs",
  "scripts/check-deployment-delta-viewer.mjs",
  "scripts/check-delegation-repair.mjs",
  "scripts/check-delegation-repair-viewer.mjs",
  "scripts/check-quantization-lattice.mjs",
  "scripts/check-quantization-lattice-viewer.mjs",
  "scripts/check-quant-evidence-chains.mjs",
  "scripts/check-quant-evidence-chains-viewer.mjs",
  "scripts/check-quant-research-applicability.mjs",
  "scripts/check-accumulator-atlas.mjs",
  "scripts/check-accumulator-atlas-viewer.mjs",
  "scripts/check-requantization-fidelity.mjs",
  "scripts/check-requantization-fidelity-viewer.mjs",
  "scripts/check-kernel-witness.mjs",
  "scripts/check-kernel-witness-viewer.mjs",
  "scripts/check-channel-vitality.mjs",
  "scripts/check-channel-vitality-viewer.mjs",
  "scripts/check-rounding-equivalence.mjs",
  "scripts/check-rounding-equivalence-viewer.mjs",
  "scripts/check-accumulator-reachability.mjs",
  "scripts/check-accumulator-reachability-viewer.mjs",
  "scripts/check-numerical-abi-propagation.mjs",
  "scripts/check-numerical-abi-propagation-viewer.mjs",
  "scripts/check-input-counterexample.mjs",
  "scripts/check-input-counterexample-viewer.mjs",
  "scripts/check-preprocessing-realizability.mjs",
  "scripts/check-preprocessing-realizability-viewer.mjs",
  "scripts/check-preprocessing-consequence.mjs",
  "scripts/check-preprocessing-consequence-viewer.mjs",
  "scripts/check-contract-migration.mjs",
  "scripts/check-contract-migration-viewer.mjs",
  "scripts/check-residual-step-response.mjs",
  "scripts/check-residual-step-response-viewer.mjs",
  "scripts/check-residual-contract-distortion.mjs",
  "scripts/check-residual-contract-distortion-viewer.mjs",
  "scripts/check-onnx-quantization-contract.mjs",
  "scripts/check-onnx-type-sparse-contract.mjs",
  "scripts/check-onnx-shape-inference.mjs",
  "scripts/check-onnx-runtime-shape-binding.mjs",
  "scripts/check-onnx-operation-cost.mjs",
  "scripts/check-onnx-container-inference.mjs",
  "scripts/check-onnx-ml-value-inference.mjs",
  "scripts/check-onnx-ml-label-encoder.mjs",
  "scripts/check-onnx-ml-svm.mjs",
  "scripts/check-onnx-ml-tree-ensemble.mjs",
  "scripts/check-onnx-tfidf-vectorizer.mjs",
  "scripts/check-onnx-schema-legality.mjs",
  "scripts/check-onnx-extended-shape-inference.mjs",
  "scripts/check-onnx-shape-scope.mjs",
  "scripts/check-onnx-domain-analysis.mjs",
  "scripts/check-kernel-inspector-contract.mjs",
  "scripts/check-runtime-arena-memory.mjs",
  "scripts/check-runtime-arena-viewer.mjs",
  "scripts/check-runtime-profile-adapter.mjs",
  "scripts/check-runtime-data-movement-evidence.mjs",
  "scripts/check-ort-native-capture.mjs",
  "scripts/check-ort-build-attestation.mjs",
  "scripts/check-runtime-backend-evidence-ledger.mjs",
  "scripts/check-calibration-validation-ledger.mjs",
  "scripts/check-calibration-validation-viewer.mjs",
  "scripts/check-tflite-runtime-info-adapter.mjs",
  "scripts/check-tflite-profile-info-adapter.mjs",
  "scripts/check-xnnpack-selector-evidence.mjs",
  "scripts/check-xnnpack-delegate-rulepack.mjs",
  "scripts/check-tflite-delegate-rulepack.mjs",
  "scripts/check-ort-rulepack-generated.mjs",
  "scripts/check-ort-reduced-operator-config.mjs",
  "scripts/check-ort-artifact-precheck.mjs",
  "scripts/check-runtime-contract.mjs",
  "scripts/check-sw-assets.mjs",
  "scripts/check-service-worker-lifecycle.mjs",
  "scripts/check-offline-device-controller.mjs",
  "scripts/check-sw-version.mjs",
  "scripts/check-size-utils.mjs",
  "scripts/check-private-wasm-registry.mjs",
  "scripts/check-private-wasm-contract.mjs",
  "scripts/check-ci-deploy-contract.mjs",
  "scripts/check-git-privacy.mjs",
  "scripts/check-worker-config.mjs",
];

const fromValue = process.argv.find((value) => value.startsWith("--from="))?.slice(7)
  || (process.argv.includes("--from") ? process.argv[process.argv.indexOf("--from") + 1] : "");
const throughValue = process.argv.find((value) => value.startsWith("--through="))?.slice(10)
  || (process.argv.includes("--through") ? process.argv[process.argv.indexOf("--through") + 1] : "");
const startIndex = fromValue ? CHECKS.indexOf(fromValue) : 0;
if (startIndex < 0) {
  throw new Error(`Unknown --from check: ${fromValue}`);
}
const throughIndex = throughValue ? CHECKS.indexOf(throughValue) : CHECKS.length - 1;
if (throughIndex < 0) throw new Error(`Unknown --through check: ${throughValue}`);
if (throughIndex < startIndex) throw new Error("--through check must not precede --from check.");
const selected = CHECKS.slice(startIndex, throughIndex + 1);
const timeoutMs = Number.parseInt(process.env.DEEPBOM_CHECK_TIMEOUT_MS || "600000", 10);
for (const [offset, check] of selected.entries()) {
  const position = startIndex + offset + 1;
  const started = performance.now();
  const [script, ...args] = check.split(/\s+/);
  console.log(`\n[${position}/${CHECKS.length}] ${check}`);
  await runNode(script, args, { timeoutMs });
  console.log(`[${position}/${CHECKS.length}] completed in ${((performance.now() - started) / 1000).toFixed(1)}s`);
}

console.log(`All selected local checks passed (${startIndex + 1}-${throughIndex + 1}/${CHECKS.length}; ${selected.length} checks).`);
