const CACHE_NAME = "tflite-wasm-static-audit-v541";
const APP_CACHE_PREFIX = "tflite-wasm-static-audit-v";
const APP_ASSETS = [
  "./",
  "./index.html",
  "./medical.html",
  "./admin.html",
  "./auth-complete.html",
  "./auth-complete.js",
  "./test.html",
  "./test.js",
  "./styles.css",
  "./research-labs.css",
  "./app-shell.css",
  "./device-workspace.css",
  "./report-workspace.css",
  "./explorer-redesign.css",
  "./explorer-evidence.css",
  "./explorer-question.css",
  "./execution-placement.css",
  "./onnx-domain.css",
  "./research-theme.css",
  "./lib/theme-ui.js",
  "./NOTICE.txt",
  "./bootstrap.js",
  "./app.js",
  "./lib/analysis-depth-mode.js",
  "./lib/accelerator-binding.js",
  "./lib/accelerator-profile-switcher.js",
  "./lib/edgetpu-compiler-evidence.js",
  "./lib/litert-qualcomm-evidence.js",
  "./lib/placement-comparison.js",
  "./lib/tflite-accelerator-source-profiles.js",
  "./lib/cpu-target-binding.js",
  "./lib/offline-device-controller.js",
  "./lib/app-deepbom-workspace.js",
  "./lib/app-graph-workspace.js",
  "./lib/artifact-ir.js",
  "./lib/artifact-ir-context.js",
  "./lib/graph-ir.js",
  "./lib/graph-export.js",
  "./lib/graph-hierarchy.js",
  "./lib/evidence-treemap.js",
  "./lib/evidence-cursor.js",
  "./lib/evidence-why-drawer.js",
  "./lib/artifact-diff.js",
  "./lib/artifact-diff-view.js",
  "./lib/node-edge-evidence-overlay.js",
  "./lib/review-export.js",
  "./onnx.js",
  "./executorch.js",
  "./lib/admin-elements.js",
  "./lib/app-config.js",
  "./lib/citation-ui.js",
  "./lib/clipboard.js",
  "./lib/app-surface.js",
  "./lib/custom-target-editor.js",
  "./lib/custom-targets.js",
  "./lib/analysis.js",
  "./lib/artifact-bundle.js",
  "./lib/artifact-overview.js",
  "./lib/graph-topology.js",
  "./lib/model-glance.js",
  "./lib/explorer-decision-view.js",
  "./lib/explorer-question-view.js",
  "./lib/explorer-redesign.js",
  "./lib/redesign-codegen.js",
  "./lib/quant-evidence-view.js",
  "./lib/quant-evidence-chains.js",
  "./lib/quant-research-applicability.js",
  "./lib/node-view.js",
  "./lib/arena-viewer.js",
  "./lib/audit-progress.js",
  "./lib/static-audit-worker-client.js",
  "./lib/deepbom-worker-client.js",
  "./workers/static-audit-worker.js",
  "./workers/deepbom-analysis-worker.js",
  "./lib/audit-ui.js",
  "./lib/auth-labels.js",
  "./lib/access-policy.js",
  "./lib/auth-ui.js",
  "./lib/benchmark-ui.js",
  "./lib/build-metadata.js",
  "./lib/xnnpack-rulepack-metadata.js",
  "./lib/bundle.js",
  "./lib/dom.js",
  "./lib/deployment-frontier.js",
  "./lib/core-isolation-view.js",
  "./lib/deployment-delta.js",
  "./lib/dynamic-shape-cost.js",
  "./lib/guarded-integer-expression.js",
  "./lib/flatbuffer-reader.js",
  "./lib/onnx-dimension-expression.js",
  "./lib/onnx-operation-cost.js",
  "./lib/tensorrt-profile-cost.js",
  "./lib/delegation-repair.js",
  "./lib/quantization-lattice.js",
  "./lib/quantization-math.js",
  "./lib/contract-migration.js",
  "./lib/coreml-metadata-adapter.js",
  "./lib/coreml-compute-plan.js",
  "./lib/coreml-classical-model.js",
  "./lib/coreml-deployment-contract.js",
  "./lib/coreml-exact-integer.js",
  "./lib/coreml-neural-network.js",
  "./lib/coreml-mil-program.js",
  "./lib/llm-layer-storage.js",
  "./lib/llm-static-memory-placement.js",
  "./lib/llm-memory-feasibility.js",
  "./lib/llm-token-budget-scenario.js",
  "./lib/tensorrt-llm-source-metadata.js",
  "./lib/tensorrt-llm-contract.js",
  "./lib/coreml-blob.js",
  "./lib/residual-step-response.js",
  "./lib/residual-step-response-worker.js",
  "./lib/residual-contract-distortion.js",
  "./lib/residual-contract-distortion-worker.js",
  "./lib/accumulator-atlas.js",
  "./lib/requantization-fidelity.js",
  "./lib/kernel-witness.js",
  "./lib/kernel-witness-worker.js",
  "./lib/channel-vitality.js",
  "./lib/channel-vitality-worker.js",
  "./lib/rounding-equivalence.js",
  "./lib/rounding-equivalence-worker.js",
  "./lib/accumulator-reachability.js",
  "./lib/accumulator-reachability-worker.js",
  "./lib/accumulator-reachability-viewer.js",
  "./lib/numerical-abi-propagation.js",
  "./lib/numerical-abi-propagation-viewer.js",
  "./lib/input-counterexample.js",
  "./lib/input-counterexample-viewer.js",
  "./lib/preprocessing-realizability.js",
  "./lib/preprocessing-realizability-viewer.js",
  "./lib/preprocessing-consequence-core.js",
  "./lib/preprocessing-consequence-runtime.js",
  "./lib/preprocessing-consequence-validator.js",
  "./lib/preprocessing-consequence-viewer.js",
  "./lib/calibration-validation-ledger.js",
  "./lib/calibration-validation-view.js",
  "./lib/rgb-png.js",
  "./lib/quantization-research-suite.js",
  "./lib/download.js",
  "./lib/elements.js",
  "./lib/export-artifacts.js",
  "./lib/export-contract-view.js",
  "./lib/public-cyclonedx-export.js",
  "./lib/public-evidence-package.js",
  "./lib/evidence-package-profiles.js",
  "./lib/evidence-level-report.js",
  "./lib/evidence-package-rights.js",
  "./lib/cyclonedx-20-preview.js",
  "./lib/cyclonedx-identity.js",
  "./lib/cyclonedx-component-metadata.js",
  "./lib/corpus-validation-provenance.js",
  "./lib/public-key-signature.js",
  "./lib/signing-key-trust.js",
  "./lib/onnx-external-data-status.js",
  "./reference/quant-policy-boundary-validation.v1.json",
  "./lib/interface-contract.js",
  "./lib/format.js",
  "./lib/findings-viewer.js",
  "./lib/format-audit-tabs.js",
  "./lib/finding-contract.js",
  "./lib/graph-ui.js",
  "./lib/graph-layout.js",
  "./lib/hash.js",
  "./lib/insights.js",
  "./lib/markdown-report.js",
  "./lib/account-ui.js",
  "./lib/metadata-model-adapters.js",
  "./lib/gguf-backend-contract.generated.js",
  "./lib/gguf-backend-contract.js",
  "./lib/gguf-codebooks.generated.js",
  "./lib/gguf-runtime-environment.js",
  "./lib/hf-safetensors-contract.js",
  "./lib/safetensors-quantization-contract.js",
  "./lib/safetensors-quantization-export.js",
  "./lib/safetensors-quantization-view.js",
  "./lib/tensor-numerical-integrity.js",
  "./lib/transformer-architecture-projection.js",
  "./lib/llm-specialized-projection.js",
  "./lib/on-device-llm-runtime-manifest.js",
  "./lib/model-file.js",
  "./lib/serialized-tensor-view.js",
  "./lib/sample-models.js",
  "./lib/sample-library.js",
  "./lib/sample-verification.js",
  "./lib/tensor-inventory.js",
  "./lib/onnx-domain-analysis.js",
  "./lib/onnx-ort-extension-shape-inference.js",
  "./lib/onnx-ort-matmul-shape-inference.js",
  "./lib/onnx-ort-recurrent-shape-inference.js",
  "./lib/onnx-ort-transformer-shape-inference.js",
  "./lib/onnx-opset-imports.js",
  "./lib/onnx-domain-viewer.js",
  "./lib/onnx-container-inference.js",
  "./lib/onnx-ml-normalizer.js",
  "./lib/onnx-ml-normalizer-conformance.js",
  "./lib/onnx-ml-scaler.js",
  "./lib/onnx-ml-imputer.js",
  "./lib/onnx-ml-one-hot-encoder.js",
  "./lib/onnx-ml-label-encoder.js",
  "./lib/onnx-ml-label-encoder-conformance.js",
  "./lib/onnx-ml-svm.js",
  "./lib/onnx-ml-svm-conformance.js",
  "./lib/onnx-ml-tree-ensemble.js",
  "./lib/onnx-ml-tree-ensemble-conformance.js",
  "./lib/onnx-ml-linear-model.js",
  "./lib/onnx-ml-value-inference.js",
  "./lib/onnx-extended-shape-inference.js",
  "./lib/onnx-schema-legality.js",
  "./lib/onnx-einsum-contract.js",
  "./lib/onnx-shape-inference.js",
  "./lib/onnx-runtime-shape-binding.js",
  "./lib/onnx-shape-ops.js",
  "./lib/onnx-shape-schema-generated.js",
  "./lib/onnx-sparse-tensor.js",
  "./lib/onnx-tfidf-vectorizer.js",
  "./lib/onnx-type-proto.js",
  "./lib/onnx-benchmark.js",
  "./lib/onnx-external-data.js",
  "./lib/ort-compatibility-evidence.js",
  "./lib/ort-reduced-operator-config.js",
  "./lib/ort-build-attestation.js",
  "./lib/ort-selected-build-binding.js",
  "./lib/kernel-inspector.js",
  "./lib/runtime-memory.js",
  "./lib/sha256-sync.js",
  "./lib/performance-visuals.js",
  "./lib/on-device-llm-contract.js",
  "./lib/on-device-llm-view.js",
  "./lib/llm-device-feasibility-view.js",
  "./lib/research-visuals.js",
  "./lib/protocols.js",
  "./lib/reason-codes.js",
  "./lib/format-evidence-scope.js",
  "./lib/format-capability-view.js",
  "./lib/execution-placement-view.js",
  "./lib/backend-placement-projection.js",
  "./lib/tensorrt-source-metadata.js",
  "./lib/tensorrt-engine-inspector.js",
  "./lib/tensorrt-cyclonedx-properties.js",
  "./lib/tensorrt-static-preflight.js",
  "./lib/runtime-backend-evidence-ledger.js",
  "./lib/execution-placement-evidence.js",
  "./lib/executorch-build-binding.js",
  "./lib/format-workflow-ui.js",
  "./lib/privacy-ui.js",
  "./lib/modal-accessibility.js",
  "./lib/research.js",
  "./lib/report-context.js",
  "./lib/report-change-analysis.js",
  "./lib/report-engineering-entry.js",
  "./lib/report-engineering.js",
  "./lib/report-engineering-deployment.js",
  "./lib/report-engineering-derivations.js",
  "./lib/report-engineering-kernels.js",
  "./lib/report-engineering-onnx.js",
  "./lib/report-engineering-quant-research.js",
  "./lib/report-engineering-safetensors-quantization.js",
  "./lib/report-engineering-serialized.js",
  "./lib/report-engineering-tflite-subgraphs.js",
  "./lib/report-engineering-tflite-delegates.js",
  "./lib/report-execution-placement.js",
  "./lib/report-findings.js",
  "./lib/report-integrity.js",
  "./lib/report-metadata.js",
  "./lib/report-quantization-contracts.js",
  "./lib/report-regulatory-entry.js",
  "./lib/report-regulatory.js",
  "./lib/report-security-posture.js",
  "./lib/report-sections.js",
  "./lib/quantization-contract-summary.js",
  "./lib/session-evidence.js",
  "./lib/public-export.js",
  "./lib/public-verification-ui.js",
  "./lib/public-verification-manifest.js",
  "./lib/report-store.js",
  "./lib/report-utils.js",
  "./lib/runtime.js",
  "./lib/runtime-module-loader.js",
  "./lib/runtime-evidence-closure.js",
  "./lib/runtime-evidence-sidecar.js",
  "./lib/runtime-evidence-controller.js",
  "./lib/runtime-profile-adapter.js",
  "./lib/runtime-data-movement-evidence.js",
  "./lib/runtime-profile-modal.js",
  "./lib/tflite-runtime-info-adapter.js",
  "./lib/tflite-profile-info-adapter.js",
  "./lib/tflite-build-configuration-binding.js",
  "./lib/tflite-delegate-compatibility.js",
  "./lib/tflite-delegate-rulepack-metadata.js",
  "./lib/service-worker.js",
  "./lib/status.js",
  "./lib/storage.js",
  "./lib/strict-json.js",
  "./lib/telemetry.js",
  "./lib/tflite-benchmark.js",
  "./lib/visual-export.js",
  "./lib/influence.js",
  "./lib/weight-hist.js",
  "./lib/workflow-copy.js",
  "./lib/workflow-controller.js",
  "./lib/workspace-navigation.js",
  "./lib/xnnpack-selector-evidence.js",
  "./lib/zip.js",
  "./admin.js",
  "./manifest.webmanifest",
  "../pkg/tflite_wasm_audit.js",
  "../pkg/tflite_wasm_audit_bg.wasm",
];

// Keep installation bounded. The complete module graph remains cacheable and
// is stored as each format, research view, or runtime is actually requested.
const APP_SHELL_ASSETS = [
  "./",
  "./index.html",
  "./medical.html",
  "./styles.css",
  "./research-labs.css",
  "./app-shell.css",
  "./device-workspace.css",
  "./report-workspace.css",
  "./explorer-redesign.css",
  "./explorer-evidence.css",
  "./explorer-question.css",
  "./onnx-domain.css",
  "./research-theme.css",
  "./lib/theme-ui.js",
  "./NOTICE.txt",
  "./app.js",
  "./manifest.webmanifest",
  "../pkg/tflite_wasm_audit.js",
  "../pkg/tflite_wasm_audit_bg.wasm",
];

const RUNTIME_CACHEABLE_SUFFIXES = [
  "/node_modules/@litertjs/core/dist/index.js",
  "/node_modules/@litertjs/wasm-utils/dist/index.js",
  "/node_modules/@litertjs/core/wasm/litert_wasm_compat_internal.js",
  "/node_modules/@litertjs/core/wasm/litert_wasm_compat_internal.wasm",
  "/node_modules/@litertjs/core/wasm/litert_wasm_internal.js",
  "/node_modules/@litertjs/core/wasm/litert_wasm_internal.wasm",
  "/node_modules/@litertjs/core/wasm/litert_wasm_jspi_internal.js",
  "/node_modules/@litertjs/core/wasm/litert_wasm_jspi_internal.wasm",
  "/node_modules/onnxruntime-web/dist/ort.wasm.min.mjs",
  "/node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.mjs",
  "/node_modules/onnxruntime-web/dist/ort-wasm-simd-threaded.wasm",
];

const AUTHENTICATED_ASSET_PREFIXES = [
  "/web/protected/",
];

const AUTHENTICATED_ASSET_PATHS = new Set([
  "/web/lib/report-raw-entry.js",
  "/web/lib/report-bundle.js",
  "/web/lib/report-evidence.js",
  "/web/lib/report-export-contracts.js",
  "/web/lib/report-mlbom.js",
  "/web/lib/report-mlbom-compat.js",
  "/web/lib/report.js",
  "/web/lib/report-conformance.js",
  "/web/lib/report-conformance-runtime-helpers.js",
  "/web/lib/report-conformance-onnx.js",
  "/web/lib/report-conformance-serialized-containers.js",
  "/web/lib/report-conformance-ort-runtime.js",
  "/web/lib/report-conformance-onnx-tfidf.js",
  "/web/lib/report-conformance-onnx-tree.js",
]);

const CACHEABLE_SUFFIXES = [
  ...APP_ASSETS.map(assetToPathSuffix),
  ...RUNTIME_CACHEABLE_SUFFIXES,
];

function assetToPathSuffix(asset) {
  if (asset === "./") return "/web/";
  if (asset.startsWith("./")) return `/web/${asset.slice(2)}`;
  if (asset.startsWith("../")) return `/${asset.slice(3)}`;
  return asset;
}

function isAuthenticatedAssetPath(pathname) {
  return AUTHENTICATED_ASSET_PATHS.has(pathname)
    || AUTHENTICATED_ASSET_PREFIXES.some((prefix) => pathname.startsWith(prefix));
}

self.addEventListener("install", (event) => {
  const publicAssets = APP_SHELL_ASSETS.filter((asset) => !isAuthenticatedAssetPath(assetToPathSuffix(asset)));
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(publicAssets)),
  );
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    // A page can otherwise retain an older eager module graph while a newly
    // activated worker serves replacement lazy modules. Any prior DeepBOM app
    // cache therefore requires one atomic navigation after the cache swap.
    const requiresAtomicReload = keys.some((key) =>
      key.startsWith(APP_CACHE_PREFIX) && key !== CACHE_NAME);
    await Promise.all(keys.filter((key) => key !== CACHE_NAME).map((key) => caches.delete(key)));
    await self.clients.claim();
    if (!requiresAtomicReload) return;
    const windows = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
    await Promise.all(windows.map((client) => client.navigate(client.url).catch(() => null)));
  })());
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (isAuthenticatedAssetPath(url.pathname)) {
    return;
  }
  const isAppAsset = CACHEABLE_SUFFIXES.some((suffix) => url.pathname.endsWith(suffix));

  if (!isAppAsset || event.request.method !== "GET") {
    return;
  }

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((response) => {
        if (response.ok) {
          const copy = response.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, copy));
        }
        return response;
      });
    }),
  );
});
